// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3TRjloHj7Ek4cZ1gRNIBaeG7mvmx6bKo',
    appId: '1:786014555497:web:73990168951218021101f8',
    messagingSenderId: '786014555497',
    projectId: 'plantaeproject-f4a8c',
    authDomain: 'plantaeproject-f4a8c.firebaseapp.com',
    storageBucket: 'plantaeproject-f4a8c.firebasestorage.app',
    measurementId: 'G-VKNV03648V',
    databaseURL: 'https://plantaeproject-f4a8c-default-rtdb.firebaseio.com/',

  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-qmL9HFzklt45_VEPGZ5V5yZuP1ahUj0',
    appId: '1:786014555497:android:0752f3d8d6ced7221101f8',
    messagingSenderId: '786014555497',
    projectId: 'plantaeproject-f4a8c',
    storageBucket: 'plantaeproject-f4a8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOseDPIJFOSsLniGPFwWAj0AesQ8CzfPk',
    appId: '1:786014555497:ios:7cd1ed8ef7c8966e1101f8',
    messagingSenderId: '786014555497',
    projectId: 'plantaeproject-f4a8c',
    storageBucket: 'plantaeproject-f4a8c.firebasestorage.app',
    iosBundleId: 'com.example.plantaeProject',
  );
}
